# Generated by Django 3.0 on 2022-05-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('Sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('Dsr_no', models.CharField(max_length=250)),
                ('Voucher_no', models.CharField(max_length=250)),
                ('Recipt_date', models.DateField()),
                ('supplier_name_adress', models.CharField(max_length=500)),
                ('rv_no', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('qty_recived', models.IntegerField()),
                ('qty_issued', models.IntegerField()),
                ('qty_balanced', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('current_locaton', models.CharField(choices=[('lab1', 'Lab1'), ('lab2', 'Lab2'), ('lab3', 'Lab3')], default=None, max_length=10)),
                ('depriciation_cost', models.IntegerField()),
            ],
        ),
    ]
