# Generated by Django 3.0 on 2022-05-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='current_locaton',
            field=models.CharField(max_length=20),
        ),
    ]
